import './styles/reset.css';
import type { User } from './api/structure/user';
import * as schema from './database/schema';
import './styles/base.css';
import MyButtonComponent from './components/button';
import { offset } from './database/utils';
import NextAuth from 'next-auth';
import './styles/theme.css';
import { named, type ExternalType } from 'external-module';
import * as fs from 'fs';
import type { Metadata } from 'next';
import http from 'node:http';
import { mkdir } from 'node:fs';
import React, { useState, type ComponentProps, useEffect } from 'react';
import './styles/globals.css';
