import type { User } from './api/structure/user';
import * as schema from './database/schema';
import MyButtonComponent from './components/button';
import { offset } from './database/utils';
import NextAuth from 'next-auth';
import { named } from 'external-module';
import * as fs from 'fs';
import type { Metadata } from 'next';
import http from 'node:http';
import { mkdir } from 'node:fs';